### ISSUE TITLE
docs(advanced): rewrite & expand

### ISSUE THREAD

**Issue by jamesericdavidson** [gokarna-theme/gokarna-hugo#277]
Building from #243. Track requirements for docs overhaul:

- [ ] Define Basic vs. Advanced criteria
- [ ] Remove repetition with Basics
  - [ ] Test Basic <-> Advanced links
- [ ] Add Lighthouse best practices (see discussion in #250)
  - [ ] Headings (impacts Table of Contents config, specifically `startLevel = 1`)
  - [ ] Image size and format (i.e. add lossy formats to `static`, convert/resize in code)
- [ ] Add GitInfo/Lastmod usage
- [ ] Explain the role of `description` across Gokarna (home, pages)
  - [ ] Add to archetype (?)
- [ ] Add hugo module as an installation method
  - [ ] Duplicate in README
- Translation and multilingual support
  - [ ] Choose one language
  - [ ] Support multiple languages across your site
- [ ] Asset compression
  - [ ] [Ahead-of-time](https://blog.cloudbending.dev/posts/gitlab-pages-compression/) (requires the web server to check for existing files, see [Codeberg Pages](https://codeberg.org/Codeberg/pages-server/pulls/387))
  - [ ] Just-in-time ([Cloudflare](https://discourse.gohugo.io/t/what-options-do-we-have-for-gzip/1477), [GitHub Pages](https://webmasters.stackexchange.com/questions/56561/is-gzip-compression-available-for-github-pages), Netlify, etc.)
- [ ] Check pages are indexing with Google Search Console
  - [ ] `sitemap.xml`
  - [ ] [Sitemap methods](https://gohugo.io/templates/sitemap/)
- [Broader SEO techniques](https://www.ranktracker.com/blog/hugo-seo/)
  - [ ] How to compose URLs
  - [ ] Lazy loading images
  - [ ] Internal links (between pages) and breadcrumbs
  - [ ] Using analytics
  - [ ] Structured data
- [ ] Add #215 
  - [ ] Close the issue

Please comment below with more suggestions :slightly_smiling_face:

**Comment by jamesericdavidson** [comment]
Copied from #287 

---

## Add hugo module as an installation method

Instructions to add the theme via `git clone` were removed in #243. While the [Hugo quick start guide](https://gohugo.io/getting-started/quick-start/#commands) relies on the `git submodule` flow for adding a theme, Hugo also supports module management using Go.

## Guides

- https://www.nickgracilla.com/posts/master-hugo-modules-managing-themes-as-modules/
- https://gohugo.io/hugo-modules/use-modules/

## To-do

- [ ] optional: rm `theme` key from `config.toml` (or `hugo.toml`)
- [ ] add `[module]` section to `config.toml`

---

Candidate for Advanced, as this requires `go` in addition to `hugo` and `git`. The Git flow is also simpler, and more readily understood by developers.

However, should feature as a snippy "[or install] as a Hugo module" hyperlink in Basics.

**Comment by JimOswick** [comment]
Not planning on picking this back up after the #335 breakage
